name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: Build Magisk Module
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare files
      run: |
        chmod +x gradlew
        chmod +x compile.sh
    - name: Compile
      run: ./compile.sh
    - name: Upload Result
      uses: actions/upload-artifact@v2
      with:
        name: ClearLineage.zip
        path: ClearLineage.zip
        if-no-files-found: error
